### ISSUE TITLE
:memo: Modif README pour decrire l'application

### ISSUE THREAD

**Issue by Thom988** [labz-nc/app-test#4]
# A propos

Pour le début l'app, mettre à jour le read me

# :dart: Objectifs : 

- [ ] Donner une description de l'app
- [ ] Créer une PR
- [ ] Tester sur les serveurs si ça marche

**Comment by Thom988** [comment]
Let's go les gars :rocket:

**Comment by fanthofe** [comment]
> Let's go les gars 🚀

Yeahhh

**Comment by Thom988** [comment]
@Nosh988 bouge ton cul

**Comment by Nosh988** [comment]
> @Nosh988 bouge ton cul

j'arrive rapidement :fire:

**Comment by Nosh988** [comment]
C'est bon modif faites 👍
